# Generated by Django 6.0.1 on 2026-01-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100, verbose_name='f001_item')),
                ('descripcion', models.CharField(max_length=100, verbose_name='f001_descripcion')),
                ('cantidad', models.IntegerField(verbose_name='f001_cantidad')),
                ('barras', models.CharField(max_length=100, verbose_name='f001_barras')),
                ('atrb1', models.CharField(max_length=100, verbose_name='f001_atrb1')),
                ('atrb2', models.CharField(max_length=100, verbose_name='f001_atrb2')),
                ('habilitado', models.BooleanField(verbose_name='f001_habilitado')),
                ('creacion', models.DateTimeField(verbose_name='f001_creacion')),
                ('actualizacion', models.DateTimeField(verbose_name='f001_actualizacion')),
            ],
        ),
    ]
